### ISSUE TITLE
Expected lua numbers on line 36

### ISSUE THREAD

**Issue by ghost** [lpawlak1/vim-simplest-todo#3]
Hi,

Im currently getting this error on adding a task with 'a' on a empty list:
```
E5108: Error executing lua ...nvim/plugged/vim-simplest-todo/lua/vim_todo/api_todo.lua:36: Expected lua number
```
Ive looked into the sourcecode and (im not a lua developer) but it seems like if the index is null, it takes the current selecton from popup as index.
But somehow popup does not return that and it results in the error above.

**Comment by ghost** [comment]
It seems like popup:get_current_selection() doesnt return anything besides nil.
my current workaround is this:
```
    if index == nil then index, line = popup:get_current_selection() end
    if index == nil then index = 0 end
    if line == nil then line = 0 end
```

**Comment by lpawlak1** [comment]
Not anymore :)
