### ISSUE TITLE
Todos are not saved

### ISSUE THREAD

**Issue by ghost** [lpawlak1/vim-simplest-todo#4]
I dont know why, but whatever i do, my todos are not being saved.
At the moment i do:
1. <leader>o to open the ToDo List
2. a to add a Testtask
3. Enter to save the task
4. q with Y to save the list
5. <leader>o again
6. ToDos are gone :(

**Comment by ghost** [comment]
By removing "silent" from api_todos.lua i found out that "icon" missing was the issue.

But that alone didnt solve my issue... sadly:
```
Run-time error 103
File saveFile.icn; Line 13
string expected
offending value: &null
Traceback:
main()
find(&null,"[\xe2\x9c\x97] 21/04/21, ...",&null,&null) from line 13 in saveFile.icn
```

**Comment by lpawlak1** [comment]
Can you show me main directory with files ```...nvim/plugged/vim-simplest-todo/```?

**Comment by lpawlak1** [comment]
Check if anything changed from previous behaviour :)

**Comment by ghost** [comment]
Works! Nice!
