### ISSUE TITLE
Check status is not being saved

### ISSUE THREAD

**Issue by ghost** [lpawlak1/vim-simplest-todo#5]
TODO's are automatically checked as done on loading the board with Leader+o.

1. Open TODO's with Leader+o
2. Create new task with "a" and name "Test"
3. Close with ESC and "Y" to save
4. Open TODO's again
5. Todo is now marked as done.
If you mark the todo as undone again, it will be marked as done if you open the TODO's again.

**Comment by lpawlak1** [comment]
That's a bug in python script.

**Comment by ghost** [comment]
Thanks for the change! Fixed it!

**Comment by ghost** [comment]
Sadly now its the other way around... If i mark a TODO as done, the "done" status is not being saved and reset on reopening the TODO's

**Comment by lpawlak1** [comment]
I'm unable to repreduce the bug right now to unknown reasons
